### ISSUE TITLE
Include <functional>

### ISSUE THREAD

**Issue by karulont** [Cylix/tacopie#13]
`[ 11%] Building CXX object CMakeFiles/tacopie.dir/sources/utils/thread_pool.cpp.o                  
In file included from /home/karl/appserver/cpp_redis/tacopie/sources/utils/thread_pool.cpp:24:0:  
/home/karl/appserver/cpp_redis/tacopie/includes/tacopie/utils/thread_pool.hpp:48:16: error: ‘function’ in namespace ‘std’ does not name a template type
   typedef std::function<void()> task_t;`

Please add include to `<fuctional>`.

**Comment by Cylix** [comment]
Hi,

thanks for reporting this issue: I just submitted a fix :)

While I close this issue, please let me know if you have any other problem and do not hesitate to reopen this ticket if necessary.

Best!
