### ISSUE TITLE
if obj  outputs to same path,will make error on the link. 

### ISSUE THREAD

**Issue by yuangu** [Cylix/tacopie#21]
严重性	代码	说明	项目	文件	行	禁止显示状态
警告	MSB8027	Two or more files with the name of tcp_socket.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are ..\Classes\socket\tacopie\network\common\tcp_socket.cpp, ..\Classes\socket\tacopie\network\unix\tcp_socket.cpp, ..\Classes\socket\tacopie\network\windows\tcp_socket.cpp.	test	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets	936

**Comment by Cylix** [comment]
Erf, MSVC is really annoying...

Seems like it does not match the source tree when it comes to generating output files, leading to common/tcp_socket.cpp and windows/tcp_socket.cpp both generating tcp_socket.o at the same location...

I checked online, and the only solution is to manually change the MSVC settings. Apparently, there is no way to automate with cmake.

So I'll simply rename the files to make sure that there is no source files with conflicting names.

I'll submit a fix ASAP.

Thanks for reporting this issue btw!

Best

**Comment by Cylix** [comment]
I just submitted a fix on the master branch.
If you happen to try it, let me know if it solved your issue.

Thanks again for reporting the issue and do not hesitate to open new ones if necessary.

Best!
