### ISSUE TITLE
Wiki possibly out of date for newest VS15 (2017)

### ISSUE THREAD

**Issue by IsoPippel** [Cylix/tacopie#25]
Hi, I encountered problem on both my machines when trying to build cpp_redis using methods described for windows build from that repo's wiki. It turned out that the issue was regarded to Winsock2, which is related to this project.
I was getting errors like "undefined external symbol _impl_socket ..." form object files built by tacopie (120+ of them), upon trying to link my project to already built .libs .
It appears that VS15 (VS 2017) and CMake dont get along well, and generated projects miss linkage with ws2_32, that is present in CMakeLists.
Adding it manually via 
(tacopie)`Project->Properties->Librarian->Additional Dependencies->`(input)`ws2_32.lib` seemed to solve the problem.
Cheers!

> Some specifics:
> Visual Studio 2017 15.3.0, Visual Studio Tools for CMake 1.0
> Project files generated separately by CMake v 3.8.0

**Comment by Cylix** [comment]
Hi,

Thanks a lot for reporting this issue.
As I mostly develop on unix based platform, these are hard to catch errors for me.

I'll add a note in the documentation.
Moreover, I'm also planning to include solutions files in the repository of both tacopie and cpp_redis as some people suggested in the issues, that should solve some CMake related issues.

Best
