### ISSUE TITLE
Windows dynamic port range

### ISSUE THREAD

**Issue by AkumuRu** [Cylix/tacopie#27]
Hello,

First, I'd like to say I find "tacopie" a very well written and documented library. It is hard to find something this good and self-contained these days.

My plan is to bind tcp_server to any port available in the system. I did not find any documented way of doing this with tacopie, while Winsock Reference for `bind()` function says: "For TCP/IP, if the port is specified as zero, the service provider assigns a unique port to the application from the dynamic client port range."

I have tried passing 0 as a port value to `tcp_server.start()` function:

```
tacopie::tcp_server server;
server.start("127.0.0.1", 0, callback);
```
However, this will fail inside `tcp_socket::create_socket_if_necessary()` function throwing exception due to following ternary operator:
```
m_fd   = socket(m_port == 0 ? AF_UNIX : AF_INET, SOCK_STREAM, 0);
```

Is there a documented way to achieve this with tacopie that I am not aware of?
Thank you.

**Comment by Cylix** [comment]
Hi,

I'm happy that `tacopie` brings you some satisfaction :)

The ternary is unnecessary on windows as unix sockets are not supported technically on windows.
I'll make a small change to keep AF_INET on windows, even with a 0 port.

Best

**Comment by Cylix** [comment]
I just pushed the fix.
Do not hesitate to re-open this issue if the fix does not solve your problem though.

Best :)
