### ISSUE TITLE
when connect timeout is 0,  connnect fail on same operating systems.

### ISSUE THREAD

**Issue by yuangu** [Cylix/tacopie#32]
Some operating systems (such as IOS),  socket defaults to non blocking. When the connect set to timeout is 0, the connection will fail.

sorry for my poor english.^_^

**Comment by Cylix** [comment]
Hi,

Thanks for reporting this issue and sorry for the delay to get back to you!
That's indeed a good observation, I'm going to have a look into this to fix it ASAP :)

Best

**Comment by Cylix** [comment]
Hi,

Sorry for the delay to process this issue.
This should now be fixed: I made sure that the socket is always in blocking mode if no timeout is defined.
If you happen to test the fix, let me know if it works on your side or not.

Best
