### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [Cylix/tacopie#35]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by Cylix** [comment]
Hi,

Thanks for opening this ticket.
Unfortunately, I do not have the time to set up this and to maintain it.
Furthermore, there are plenty of package manager, so it is pretty hard to figure out which out should be officially supported, and which shouldn't.

However, you, or any other person interested, are free to set it up and to push me a PR, I would be happy to merge it.

Thanks
