### ISSUE TITLE
Tacopie client: UDP? 

### ISSUE THREAD

**Issue by Oleg26Dev** [Cylix/tacopie#44]
1. Does Tacopie client work with non-Tacopie servers ?
2. I'd like to connect to GrayLog server and send log records in Gelf format
3. I'd like to send UDP messages

**Comment by Cylix** [comment]
Hi,

Unfortunately there is no UDP support as of now.
I have plans to add that support, but I do not have enough time as of now to do it. Pull Requests are welcomed though.

For the question #2, you can setup your own logger as described in the [wiki](https://github.com/Cylix/tacopie/wiki/Logger).

I'm closing this issue but feel free to re-open it if you relevant.

Best
