### ISSUE TITLE
How can I compile tacopie with Qt Creator?

### ISSUE THREAD

**Issue by GasparVardanyan** [Cylix/tacopie#52]

**Comment by Cylix** [comment]
Hi,

I am not so familiar with Qt Creator.
I'd suppose you would have to configure your `.pro` file if you are using one.
I guess one way could be to download this library and follow the build steps to generate the .a/.lib file depending on your platform, then to configure your application to link the library by specifying the library name as well as the library and include location.

Let me know if you need further assistance,

Best
