### ISSUE TITLE
Trying to serve html to browser on tacopie server

### ISSUE THREAD

**Issue by vivekvrao** [Cylix/tacopie#6]
I am trying to serve up some html content to a browser over a tacopie server.  This was my message handler - where I tried both sync and async writes and trying to close the connection when done. Neither works, maybe because I dont understand how the write/disconnect works. Any ideas? thank you!
```
	void on_new_message(const std::shared_ptr<tacopie::tcp_client>& client, const tacopie::tcp_client::read_result& res) {
		if (res.success) {
			std::string resp = "this is the response";
			std::string fullResp = "HTTP/ 1.1 200 OK\r\nContent-Type: type/html\r\nConnection: Closed\r\n Content-Length: "
				+ std::to_string(resp.length()) + std::string("\r\n\r\n") + resp;

			std::vector<char> buf(fullResp.begin(), fullResp.end());
			client->get_socket().send(buf, fullResp.length());
			//client->async_write({ buf, nullptr });
			client->disconnect();
		}
		else {
			info("WebClient disconnected");
			client->disconnect();
		}
	}
```

**Comment by Cylix** [comment]
Hi,

Sorry for the time to reply, I finally could have a look.

I tried your code and it first worked well over curl and netcat, but apparently not with a browser (I tried chrome and safari).
So my guess was that there is an issue with the content of your request.

I double checked with the expected HTTP format, and there is indeed an issue in your response.

* `HTTP/ 1.1` There is an extra space after the `/`
* `\r\n Content-Length: `: There is an extra space Before the Content

When I changed your output into:
`HTTP/1.1 200 OK\r\nContent-Type: type/html\r\nConnection: Closed\r\nContent-Length: `

it worked perfectly fine :)

I close this issue, but feel free to re-open it if necessary :)

Best

**Comment by Cylix** [comment]
BTW, my final code is the following one:

```cpp
void
on_new_message(const std::shared_ptr<tacopie::tcp_client>& client, const tacopie::tcp_client::read_result& res) {
  if (res.success) {
    std::cout << "write" << std::endl;
    std::string resp     = "this is the response";
    std::string fullResp = "HTTP/1.1 200 OK\r\nContent-Type: type/html\r\nConnection: Closed\r\nContent-Length: "
                           + std::to_string(resp.length()) + std::string("\r\n\r\n") + resp;

    std::vector<char> buf(fullResp.begin(), fullResp.end());
    client->async_write({buf, [=](tacopie::tcp_client::write_result&) {
                           std::cout << "write cb" << std::endl;
                           client->disconnect();
                         }});
  }
  else {
    std::cout << "disconnect" << std::endl;
    client->disconnect();
  }
}
```
